#!/bin/bash
# minimal — thin outline variants, quieter look
export ICON_APPLE=󰘳 ICON_THEME=󰉦 ICON_WIDGETS=󰕰
export ICON_CLOCK=󰅐 ICON_RAM=󰘚 ICON_CPU=󰻠 ICON_TEMPS=󱃃
export ICON_WIFI=󰤨 ICON_WIFI_OFF=󰤭
export ICON_VOL_HI=󰝞 ICON_VOL_MID=󰝞 ICON_VOL_LO=󰝟 ICON_VOL_MUTE=󰸈
export ICON_BAT_CHG=󱐋 ICON_BAT_100=󰂎 ICON_BAT_75=󱊣 ICON_BAT_50=󱊢 ICON_BAT_25=󱊡 ICON_BAT_10=󰂎
export ICON_MEDIA=󰽰 ICON_PREV=󰒮 ICON_PLAY=󰐊 ICON_NEXT=󰒭
export ICON_AGENTS=󱙺 ICON_NET=󰅧 ICON_WEATHER=󰖕 ICON_SPEED=󰾅
export ICON_POMO=󱦟 ICON_CAF_ON=󰛊 ICON_CAF_OFF=󰾪 ICON_PORTS=󰈀
export ICON_MEETING=󰃰 ICON_FOCUS=󰽥 ICON_CLEAN=󰇾
export ICON_CLIP=󰨸 ICON_AURA=󰫢 ICON_JOURNAL=󰧮
export ICON_SNAP=󰁌 ICON_SWITCHES=󰨙 ICON_SHOT=󰄀 ICON_BT=󰂲
export ICON_UPDATE=󰁠
export ICON_CHEV_LEFT="<"
export ICON_CHEV_RIGHT=">"
export ICON_SHELF="[]"
