#!/bin/bash
# Palette + iconset + config, loaded from a prebuilt cache.
#
# This file is sourced by every plugin on every event, so its cost is paid many
# times a second. Reading .theme and .iconset through $(cat …) and sourcing two
# more files measured ~16ms per invocation, and every widget_on was a 5ms grep
# spawn. The cache is one flat file of assignments: no subshells, no further
# sourcing, no greps.
CONFIG_DIR="${CONFIG_DIR:-$HOME/.config/sketchybar}"
ENV_CACHE="$CONFIG_DIR/.cache/env.sh"

_env_cache_stale() {
  [ -f "$ENV_CACHE" ] || return 0
  local f
  # -nt is a bash builtin, so these comparisons cost no processes
  for f in "$CONFIG_DIR/.theme" "$CONFIG_DIR/.iconset" \
           "$CONFIG_DIR/widgets.conf" "$CONFIG_DIR/settings.conf"; do
    [ -e "$f" ] && [ "$f" -nt "$ENV_CACHE" ] && return 0
  done
  # editing a theme or iconset in place has to invalidate it too
  for f in "$CONFIG_DIR"/themes/*.sh "$CONFIG_DIR"/icons/*.sh; do
    [ -e "$f" ] && [ "$f" -nt "$ENV_CACHE" ] && return 0
  done
  return 1
}

_env_cache_build() {
  local theme iconset tmp v
  theme=$(cat "$CONFIG_DIR/.theme" 2>/dev/null || echo vice-city)
  [ -f "$CONFIG_DIR/themes/$theme.sh" ] || theme=vice-city
  iconset=$(cat "$CONFIG_DIR/.iconset" 2>/dev/null || echo nerd)
  [ -f "$CONFIG_DIR/icons/$iconset.sh" ] || iconset=nerd

  source "$CONFIG_DIR/themes/$theme.sh"
  source "$CONFIG_DIR/icons/$iconset.sh"

  mkdir -p "$CONFIG_DIR/.cache" 2>/dev/null
  tmp="$ENV_CACHE.$$"
  {
    echo "# generated by colors.sh · rewritten automatically, do not edit"
    echo "export TRANSPARENT=0x00000000"
    printf 'export THEME=%q\n' "$theme"
    printf 'export ICONSET=%q\n' "$iconset"
    for v in $(compgen -v | grep -E '^(BAR_COLOR|ITEM_BG_COLOR|POPUP_BG|POPUP_BORDER|PINK|CYAN|ORANGE|RED|PURPLE|WHITE|ICON_[A-Z0-9_]*)$'); do
      printf 'export %s=%q\n' "$v" "${!v}"
    done
    # popups are opaque: blur is off for cheap flicker-free repaints
    printf 'export POPUP_PROPS=%q\n' "popup.background.color=0xff${POPUP_BG#0x??} \
popup.background.border_color=$POPUP_BORDER \
popup.background.border_width=1 \
popup.background.corner_radius=12 \
popup.blur_radius=0 \
popup.background.shadow.drawing=on \
popup.height=26"
    # widget states as one string, so widget_on is a case match not a grep
    printf 'export WIDGETS_ON=%q\n' " $(awk -F= '$2 == "on" {printf "%s ", $1}' "$CONFIG_DIR/widgets.conf" 2>/dev/null)"
    # every setting as SETTING_<key>, so setting() is a variable read not an awk
    awk -F= '/^[a-z][a-z0-9_]*=/ {printf "export SETTING_%s=%s\n", $1, $2}' \
      "$CONFIG_DIR/settings.conf" 2>/dev/null
  } > "$tmp" 2>/dev/null && mv "$tmp" "$ENV_CACHE" 2>/dev/null || rm -f "$tmp" 2>/dev/null
}

_env_cache_stale && _env_cache_build
source "$ENV_CACHE" 2>/dev/null

# if the cache could not be written (read-only checkout, odd permissions), fall
# back to reading everything directly so the bar still comes up
if [ -z "${PINK:-}" ]; then
  export TRANSPARENT=0x00000000
  THEME=$(cat "$CONFIG_DIR/.theme" 2>/dev/null || echo vice-city)
  [ -f "$CONFIG_DIR/themes/$THEME.sh" ] || THEME=vice-city
  source "$CONFIG_DIR/themes/$THEME.sh"
  ICONSET=$(cat "$CONFIG_DIR/.iconset" 2>/dev/null || echo nerd)
  [ -f "$CONFIG_DIR/icons/$ICONSET.sh" ] || ICONSET=nerd
  source "$CONFIG_DIR/icons/$ICONSET.sh"
  export POPUP_PROPS="popup.background.color=0xff${POPUP_BG#0x??} \
popup.background.border_color=$POPUP_BORDER \
popup.background.border_width=1 \
popup.background.corner_radius=12 \
popup.blur_radius=0 \
popup.background.shadow.drawing=on \
popup.height=26"
fi

# widget toggle helper — a case match against the cached list, no process spawn
widget_on() {
  case "$WIDGETS_ON" in
    *" $1 "*) return 0 ;;
    "") grep -q "^$1=on" "$CONFIG_DIR/widgets.conf" 2>/dev/null ;;
    *) return 1 ;;
  esac
}
