spaces=off
clipboard=on
pomodoro=on
aura=on
network=on
media=off
caffeine=on
ports=on
github=off
weather=off
speedtest=off
meeting=off
focus=off
temps=off
journal=on
max_active=9
snap=on
switches=off
shot=on
bluetooth=off
extras=on
shelf=on
mic=off
